Feature/create movie detail screen
StarWarsProject/StarWars-iOS pull request #11
Opened 2022-11-29 16:59 UTC by rodrigoschar

-create detail for movies
-add automatic scroll
-last changes

2022-11-29 19:19 UTC, YawarValeriano commented on StarWars-iOS/modules/moviedetail/controllers/MovieDetailViewController.swift
> +//  Created by User on 28/11/22.
Change the User by your name

2022-11-29 19:20 UTC, YawarValeriano requested changes
The details view has to be callen on the "see details" button, not the movie list

2022-11-29 21:20 UTC, rodrigoschar commented on StarWars-iOS/modules/moviedetail/controllers/MovieDetailViewController.swift
> +//  Created by User on 28/11/22.
done!

2022-11-30 12:57 UTC, YawarValeriano approved these changes

2022-11-30 13:21 UTC, merged